apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels: # these labels are deployment labels
    app: cart
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: cart
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: cart
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cart
        image: "{{ .Values.deployment.imageURL}}:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: cart